name: Update README Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Stats SVG
        run: |
          mkdir -p assets
          curl -L "https://github-readme-stats.vercel.app/api?username=MihneaTeodorStoica&show_icons=true&rank_icon=github&include_all_commits=true&hide=stars&theme=dark" \
            -o assets/github-stats.svg
          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=MihneaTeodorStoica&layout=compact&langs_count=8&theme=dark" \
            -o assets/top-langs.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/*.svg
          git commit -m "Update README stats" || exit 0
          git push
